apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.131.0.167"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-02-26T19:47:50Z"
  generateName: mariadb-sample-5bd78c456f-
  labels:
    app: mariadb-sample
    component: data-science-pipelines
    dspa: sample
    pod-template-hash: 5bd78c456f
  name: mariadb-sample-5bd78c456f-kffct
  namespace: test
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mariadb-sample-5bd78c456f
    uid: bc6dc3b9-7102-49a0-89a6-9d50767b80f6
  resourceVersion: "43007220"
  uid: 650fccd3-4a77-4914-a3a5-d0d1da0260b9
spec:
  containers:
  - env:
    - name: MYSQL_USER
      value: mlpipeline
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: testdbsecret
    - name: MYSQL_DATABASE
      value: randomDBName
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "true"
    image: registry.redhat.io/rhel8/mariadb-103:1-188
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 3306
      timeoutSeconds: 1
    name: mariadb
    ports:
    - containerPort: 3306
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -i
        - -c
        - MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
          -e 'SELECT 1'
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 800Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mariadb-persistent-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9drtt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: hbelmiro-5-d95dd-worker-0-wccsf
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: ds-pipelines-mariadb-sa-sample
  serviceAccountName: ds-pipelines-mariadb-sa-sample
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: mariadb-persistent-storage
    persistentVolumeClaim:
      claimName: mariadb-sample
  - name: kube-api-access-9drtt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-26T19:47:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-26T19:48:06Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-26T19:48:06Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-26T19:47:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://7cbcb718009b6d58d097c0d2cc50cb07ad980f178a53b3fa075375e5fe874325
    image: registry.redhat.io/rhel8/mariadb-103:1-188
    imageID: registry.redhat.io/rhel8/mariadb-103@sha256:8654a0ef5b153fb6defc39deeefb5d62d456b603f814237dd6697b3f38b86046
    lastState: {}
    name: mariadb
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-26T19:47:59Z"
  hostIP: 192.168.1.120
  phase: Running
  podIP: 10.131.0.167
  podIPs:
  - ip: 10.131.0.167
  qosClass: Burstable
  startTime: "2024-02-26T19:47:51Z"