name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Build Linux amd64 binary
        run: GOOS=linux GOARCH=amd64 go build -o kgrep
      - name: Compress
        run: tar -czf kgrep-linux-amd64.tar.gz kgrep
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kgrep-linux-amd64.tar.gz

  publish-macos-binaries:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Build macOS amd64 binary
        run: GOOS=darwin GOARCH=amd64 go build -o kgrep-amd64
      - name: Build macOS arm64 binary
        run: GOOS=darwin GOARCH=arm64 go build -o kgrep-arm64
      - name: Compress amd64
        run: tar -czf kgrep-macos-amd64.tar.gz kgrep-amd64
      - name: Compress arm64
        run: tar -czf kgrep-macos-arm64.tar.gz kgrep-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kgrep-macos-amd64.tar.gz
            kgrep-macos-arm64.tar.gz