name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven - JDK
        run: mvn -B package -DskipTests -Pnative
      - name: Rename file
        run: mv /home/runner/work/kgrep/kgrep/target/kgrep-*-runner /home/runner/work/kgrep/kgrep/target/kgrep-linux
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/kgrep/kgrep/target/kgrep-linux
  publish-macos-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven - JDK
        run: mvn -B package -DskipTests -Pnative
      - name: Rename file
        run: mv /Users/runner/work/kgrep/kgrep/target/kgrep-*-runner /Users/runner/work/kgrep/kgrep/target/kgrep-macos
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /Users/runner/work/kgrep/kgrep/target/kgrep-macos