name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven - JDK
        run: mvn -B package -DskipTests -Pnative
      - name: Rename file
        run: mv /home/runner/work/kgrep/kgrep/target/kgrep-*-runner /home/runner/work/kgrep/kgrep/target/kgrep
      - name: Compress
        run: tar -czf /home/runner/work/kgrep/kgrep/target/kgrep-linux.tar.gz -C /home/runner/work/kgrep/kgrep/target kgrep
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/kgrep/kgrep/target/kgrep-linux.tar.gz
  publish-macos-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven - JDK
        run: mvn -B package -DskipTests -Pnative
      - name: Rename file
        run: mv /Users/runner/work/kgrep/kgrep/target/kgrep-*-runner /Users/runner/work/kgrep/kgrep/target/kgrep
      - name: Compress
        run: tar -czf /Users/runner/work/kgrep/kgrep/target/kgrep-macos.tar.gz -C /Users/runner/work/kgrep/kgrep/target kgrep
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /Users/runner/work/kgrep/kgrep/target/kgrep-macos.tar.gz