name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper tag information
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Build Linux amd64 binary
        run: |
          # Extract tag name (remove 'refs/tags/' prefix)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Build using Makefile target with proper version information
          make build-tag-version-linux-amd64 TAG=$TAG_NAME
      - name: Compress
        run: tar -czf kgrep-linux-amd64.tar.gz kgrep
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kgrep-linux-amd64.tar.gz

  publish-macos-binaries:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper tag information
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Build macOS amd64 binary
        run: |
          # Extract tag name (remove 'refs/tags/' prefix)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Build using Makefile target with proper version information
          make build-tag-version-darwin-amd64 TAG=$TAG_NAME
      - name: Build macOS arm64 binary
        run: |
          # Extract tag name (remove 'refs/tags/' prefix)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Build using Makefile target with proper version information
          make build-tag-version-darwin-arm64 TAG=$TAG_NAME
      - name: Compress amd64
        run: tar -czf kgrep-macos-amd64.tar.gz kgrep-amd64
      - name: Compress arm64
        run: tar -czf kgrep-macos-arm64.tar.gz kgrep-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kgrep-macos-amd64.tar.gz
            kgrep-macos-arm64.tar.gz